---

dist: trusty
sudo: required

language: python

install:
  - wget "https://github.com/sstephenson/bats/archive/v0.4.0.tar.gz"
  - tar -xf "v0.4.0.tar.gz"
  - sudo "bats-0.4.0/install.sh" "/usr/local"

script:
  - bats test_git_clean_branches.bats
