dist: trusty
sudo: required

language: generic

addons:
  apt:
    packages:
    - build-essential
    - shellcheck

before_install:
    - VERSION="0.4.0"
    - wget "https://github.com/sstephenson/bats/archive/v$VERSION.tar.gz"
    - tar -xf "v$VERSION.tar.gz"

install:
    - sudo bats-$VERSION/install.sh /usr/local

script:
    - shellcheck "git-"*
    - bats "tests/"*".bats"
