---

version: 2

test: &test
  steps:
    - checkout
    - run:
        name: install bats
        command: |
          apk update && apk add bats git
    - run:
        name: setup basic git configuration
        command: |
          git config --global user.name "CircleCI"
          git config --global user.email "fake@circleci.com"
    - run:
        name: Run tests
        command: |
          bats tests/*bats


jobs:
  lint:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: install shellcheck
          command: |
            apt-get update && apt-get install -y shellcheck
      - run:
          name: run shellcheck
          command: shellcheck git-*

  test-3.1:
    docker:
      - image: "bash:3.1"
    <<: *test

  test-3.2:
    docker:
      - image: "bash:3.2"
    <<: *test

  test-4.4:
    docker:
      - image: "bash:4.4"
    <<: *test


workflows:
  version: 2
  git_commands_test:
    jobs:
      - lint
      - test-3.1
      - test-3.2
      - test-4.4
